defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: hooptracker
  password:

development:
  <<: *defaults
  database: hooptracker_development

test: &test
  <<: *defaults
  database: hooptracker_test

cucumber:
  <<: *test